const $=s=>document.querySelector(s);const state={rows:[],filtered:[],page:1,size:50,letter:''};
const API_URL='https://260816-karemairodnare.vercel.app/api/v1/records.json',LOCAL_URL='api/v1/records.json';
const THAI=['ก','ข','ฃ','ค','ฅ','ฆ','ง','จ','ฉ','ช','ซ','ฌ','ญ','ฎ','ฏ','ฐ','ฑ','ฒ','ณ','ด','ต','ถ','ท','ธ','น','บ','ป','ผ','ฝ','พ','ฟ','ภ','ม','ย','ร','ล','ว','ศ','ษ','ส','ห','ฬ','อ','ฮ'];
const KEYS={province:['province','province_name','จังหวัด'],district:['district','district_name','amphoe','amphur','อำเภอ','เขต'],agency:['agency','agency_name','organization','organisation','department','หน่วยงาน']};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const primitive=v=>['string','number','boolean'].includes(typeof v);
function flatten(obj,p='',out={}){if(obj&&typeof obj==='object'&&!Array.isArray(obj)){for(const[k,v]of Object.entries(obj))flatten(v,p?`${p}.${k}`:k,out)}else if(Array.isArray(obj)){if(obj.every(primitive))out[p]=obj.join(', ');else obj.forEach((v,i)=>flatten(v,`${p}[${i}]`,out))}else out[p]=obj;return out}
function rowsFrom(x){if(Array.isArray(x))return x;if(x&&typeof x==='object'){for(const k of ['records','data','items','results'])if(Array.isArray(x[k]))return x[k];for(const v of Object.values(x))if(Array.isArray(v)&&v.length&&typeof v[0]==='object')return v}return[]}
function val(r,t){const f=flatten(r);for(const[k,v]of Object.entries(f)){const low=k.toLowerCase().split('.').pop();if(KEYS[t].some(x=>low===x.toLowerCase())&&v!=null)return String(v)}return''}
function title(r,i=0){const f=flatten(r);for(const p of ['name','full_name','ชื่อ','title','person_name','firstname','first_name']){const h=Object.entries(f).find(([k,v])=>k.toLowerCase().split('.').pop()===p&&v);if(h)return String(h[1])}return Object.values(f).find(v=>typeof v==='string'&&v.trim())||`รายการที่ ${i+1}`}
function idOf(r,i=0){return String(r.id??r.maskedId??i)}function score(r){const n=Number(r.scoreChange??r.score_change??0);return Number.isFinite(n)?n:0}function searchable(r){return Object.values(flatten(r)).filter(v=>v!=null).join(' ').toLocaleLowerCase('th')}
function options(id,type){const el=$(id),old=el.value,vs=[...new Set(state.rows.map(r=>val(r,type)).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'th'));el.innerHTML='<option value="">ทั้งหมด</option>'+vs.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if(vs.includes(old))el.value=old}
function buildAlphabet(){const present=new Set(state.rows.map(r=>title(r).trim()[0]).filter(Boolean));$('#alphabet').innerHTML='<button class="active" data-letter="">ทั้งหมด</button>'+THAI.filter(x=>present.has(x)).map(x=>`<button data-letter="${x}">${x}</button>`).join('');$('#alphabet').onclick=e=>{const b=e.target.closest('button');if(!b)return;state.letter=b.dataset.letter;$('#alphabet').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));apply()}}
function apply(){const q=$('#q').value.trim().toLocaleLowerCase('th'),p=$('#province').value,d=$('#district').value,a=$('#agency').value;let rows=state.rows.filter(r=>(!q||searchable(r).includes(q))&&(!p||val(r,'province')===p)&&(!d||val(r,'district')===d)&&(!a||val(r,'agency')===a)&&(!state.letter||title(r).trim().startsWith(state.letter)));const s=$('#sort').value;rows.sort((x,y)=>s==='name-desc'?title(y).localeCompare(title(x),'th'):s==='score-desc'?score(y)-score(x):s==='province-asc'?val(x,'province').localeCompare(val(y,'province'),'th'):title(x).localeCompare(title(y),'th'));state.filtered=rows;state.page=1;$('#activeHint').textContent=state.letter?`• ตัวอักษร ${state.letter}`:'';render()}
function summary(r){const bits=[['จังหวัด',val(r,'province')],['อำเภอ',val(r,'district')],['หน่วยงาน',val(r,'agency')]];if(r.scoreChange!==undefined)bits.push(['คะแนนเปลี่ยนแปลง',r.scoreChange]);return bits.filter(x=>x[1]!==''&&x[1]!=null).map(x=>`<span>${esc(x[0])}: ${esc(x[1])}</span>`).join('')}
function render(){const n=state.filtered.length,pages=Math.max(1,Math.ceil(n/state.size));state.page=Math.min(state.page,pages);$('#resultCount').textContent=n.toLocaleString('th-TH');const start=(state.page-1)*state.size,part=state.filtered.slice(start,start+state.size);$('#status').style.display=n?'none':'block';if(!n)$('#status').textContent='ไม่พบข้อมูลที่ตรงกับคำค้นหาหรือตัวกรอง';$('#results').innerHTML=part.map((r,j)=>`<article class="record" data-i="${start+j}"><div class="record-top"><h3>${esc(title(r,start+j))}</h3><span class="num">#${(start+j+1).toLocaleString('th-TH')}</span></div><div class="summary">${summary(r)}</div></article>`).join('');document.querySelectorAll('.record').forEach(el=>el.onclick=()=>detail(state.filtered[+el.dataset.i],+el.dataset.i));pager(pages)}
function pager(pages){const cur=state.page,nums=[];for(let i=1;i<=pages;i++)if(i===1||i===pages||Math.abs(i-cur)<=2)nums.push(i);let h=cur>1?'<button data-p="prev">‹</button>':'',last=0;for(const n of nums){if(last&&n-last>1)h+='<button disabled>…</button>';h+=`<button data-p="${n}" class="${n===cur?'active':''}">${n}</button>`;last=n}if(cur<pages)h+='<button data-p="next">›</button>';$('#pagination').innerHTML=h;$('#pagination').querySelectorAll('button:not([disabled])').forEach(b=>b.onclick=()=>{state.page=b.dataset.p==='prev'?cur-1:b.dataset.p==='next'?cur+1:+b.dataset.p;render();document.querySelector('.result-head').scrollIntoView({behavior:'smooth',block:'start'})})}
function sourceCards(r){const ss=Array.isArray(r.sources)?r.sources:[];if(!ss.length)return'';return `<section class="source-section"><h3>เอกสารต้นทาง</h3>${ss.map(s=>{const f=flatten(s),file=f.filename||f.file||f.name||'',page=f.page||f.pageNumber||f.page_number||'',url=f.url||f.href||'';return `<div class="source-card"><strong>${esc(file||'แหล่งอ้างอิง')}</strong>${page?`<span>หน้า ${esc(page)}</span>`:''}${url&&/^https?:\/\//.test(url)?`<a href="${esc(url)}" target="_blank" rel="noopener">เปิดเอกสารต้นทาง ↗</a>`:''}</div>`}).join('')}</section>`}
function detail(r,i){$('#detailTitle').textContent=title(r,i);const preferred=[['รหัส',r.id],['เลขอ้างอิง',r.maskedId],['คะแนนเปลี่ยนแปลง',r.scoreChange],['หน่วยงาน',r.agency],['อำเภอ',r.district],['จังหวัด',r.province],['สถานะ/แหล่งตรวจสอบ',r.verificationSource]].filter(([,v])=>v!==undefined&&v!==null&&v!=='');const fields=preferred.map(([k,v])=>`<div class="field"><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('');const share=`${location.origin}${location.pathname}?record=${encodeURIComponent(idOf(r,i))}`;$('#detailBody').innerHTML=`<div class="detail-actions"><button id="copyLink" class="btn-secondary">คัดลอกลิงก์รายการ</button></div><dl>${fields}</dl>${sourceCards(r)}<p class="detail-note">โปรดตรวจเอกสารต้นทางก่อนสรุปความหมายของรายการนี้</p>`;$('#detailDialog').showModal();history.replaceState(null,'',`?record=${encodeURIComponent(idOf(r,i))}`);$('#copyLink').onclick=async()=>{await navigator.clipboard.writeText(share);$('#copyLink').textContent='คัดลอกแล้ว ✓'}}
function randomRecord(){if(!state.filtered.length)return;const i=Math.floor(Math.random()*state.filtered.length);detail(state.filtered[i],i)}async function loadJson(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${url}: HTTP ${r.status}`);return r.json()}
async function boot(){let source='upstream',payload;try{payload=await loadJson(API_URL)}catch(e){console.warn(e);source='snapshot';try{payload=await loadJson(LOCAL_URL)}catch(le){$('#recordCount').textContent='โหลดข้อมูลไม่สำเร็จ';$('#sourceBadge').textContent='API และ snapshot ใช้งานไม่ได้';$('#status').textContent='ไม่สามารถโหลดข้อมูลได้';return}}state.rows=rowsFrom(payload);state.filtered=[...state.rows];$('#recordCount').textContent=`ข้อมูล ${state.rows.length.toLocaleString('th-TH')} รายการ`;$('#sourceBadge').textContent=source==='upstream'?'ข้อมูลสดจาก API ต้นทาง':'กำลังใช้ snapshot สำรอง';options('#province','province');options('#district','district');options('#agency','agency');buildAlphabet();apply();const wanted=new URLSearchParams(location.search).get('record');if(wanted){const i=state.rows.findIndex((r,n)=>idOf(r,n)===wanted);if(i>=0)detail(state.rows[i],i)}}
let timer;$('#q').oninput=()=>{clearTimeout(timer);timer=setTimeout(apply,120)};['#province','#district','#agency','#sort'].forEach(id=>$(id).onchange=apply);$('#pageSize').onchange=e=>{state.size=+e.target.value;state.page=1;render()};$('#random').onclick=randomRecord;$('#reset').onclick=()=>{$('#q').value='';['#province','#district','#agency'].forEach(x=>$(x).value='');$('#sort').value='name-asc';state.letter='';buildAlphabet();apply()};$('#clearSearch').onclick=()=>{$('#q').value='';apply();$('#q').focus()};$('#closeDialog').onclick=()=>{$('#detailDialog').close();history.replaceState(null,'',location.pathname)};$('#detailDialog').addEventListener('click',e=>{if(e.target===$('#detailDialog')){$('#detailDialog').close();history.replaceState(null,'',location.pathname)}});boot();