const $=s=>document.querySelector(s);const state={rows:[],filtered:[],page:1,size:50};
const API_URL='https://260816-karemairodnare.vercel.app/api/v1/records.json';
const LOCAL_URL='api/v1/records.json';
const KEYS={province:['province','province_name','จังหวัด'],district:['district','district_name','amphoe','amphur','อำเภอ','เขต'],agency:['agency','agency_name','organization','organisation','department','หน่วยงาน']};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const primitive=v=>['string','number','boolean'].includes(typeof v);
function flatten(obj,p='',out={}){if(obj&&typeof obj==='object'&&!Array.isArray(obj)){for(const[k,v]of Object.entries(obj))flatten(v,p?`${p}.${k}`:k,out)}else if(Array.isArray(obj)){if(obj.every(primitive))out[p]=obj.join(', ');else obj.forEach((v,i)=>flatten(v,`${p}[${i}]`,out))}else out[p]=obj;return out}
function rowsFrom(payload){if(Array.isArray(payload))return payload;if(payload&&typeof payload==='object'){for(const k of ['records','data','items','results'])if(Array.isArray(payload[k]))return payload[k];for(const v of Object.values(payload))if(Array.isArray(v)&&v.length&&typeof v[0]==='object')return v}return[]}
function val(row,type){const flat=flatten(row);for(const [k,v] of Object.entries(flat)){const low=k.toLowerCase().split('.').pop();if(KEYS[type].some(x=>low===x.toLowerCase())&&v!=null)return String(v)}return''}
function title(row,i){const f=flatten(row);const priorities=['name','full_name','ชื่อ','title','person_name','firstname','first_name'];for(const p of priorities){const hit=Object.entries(f).find(([k,v])=>k.toLowerCase().split('.').pop()===p&&v);if(hit)return String(hit[1])}const vals=Object.values(f).filter(v=>typeof v==='string'&&v.trim());return vals[0]||`รายการที่ ${i+1}`}
function searchable(row){return Object.values(flatten(row)).filter(v=>v!=null).join(' ').toLocaleLowerCase('th')}
function options(id,type){const el=$(id),old=el.value;const vals=[...new Set(state.rows.map(r=>val(r,type)).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'th'));el.innerHTML='<option value="">ทั้งหมด</option>'+vals.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if(vals.includes(old))el.value=old}
function apply(){const q=$('#q').value.trim().toLocaleLowerCase('th'),p=$('#province').value,d=$('#district').value,a=$('#agency').value;state.filtered=state.rows.filter(r=>(!q||searchable(r).includes(q))&&(!p||val(r,'province')===p)&&(!d||val(r,'district')===d)&&(!a||val(r,'agency')===a));state.page=1;render()}
function summary(r){return [['จังหวัด',val(r,'province')],['อำเภอ',val(r,'district')],['หน่วยงาน',val(r,'agency')]].filter(x=>x[1]).map(x=>`<span>${esc(x[0])}: ${esc(x[1])}</span>`).join('')}
function render(){const n=state.filtered.length,pages=Math.max(1,Math.ceil(n/state.size));state.page=Math.min(state.page,pages);$('#resultCount').textContent=n.toLocaleString('th-TH');const start=(state.page-1)*state.size,part=state.filtered.slice(start,start+state.size);$('#status').style.display=n?'none':'block';if(!n)$('#status').textContent='ไม่พบข้อมูลที่ตรงกับคำค้นหาหรือตัวกรอง';$('#results').innerHTML=part.map((r,j)=>`<article class="record" data-i="${start+j}"><div class="record-top"><h3>${esc(title(r,start+j))}</h3><span class="num">#${(start+j+1).toLocaleString('th-TH')}</span></div><div class="summary">${summary(r)}</div></article>`).join('');document.querySelectorAll('.record').forEach(el=>el.onclick=()=>detail(state.filtered[+el.dataset.i],+el.dataset.i));pager(pages)}
function pager(pages){const cur=state.page;let nums=[];for(let i=1;i<=pages;i++)if(i===1||i===pages||Math.abs(i-cur)<=2)nums.push(i);let html=cur>1?'<button data-p="prev">‹</button>':'';let last=0;for(const n of nums){if(last&&n-last>1)html+='<button disabled>…</button>';html+=`<button data-p="${n}" class="${n===cur?'active':''}">${n}</button>`;last=n}if(cur<pages)html+='<button data-p="next">›</button>';$('#pagination').innerHTML=html;$('#pagination').querySelectorAll('button:not([disabled])').forEach(b=>b.onclick=()=>{state.page=b.dataset.p==='prev'?cur-1:b.dataset.p==='next'?cur+1:+b.dataset.p;render();document.querySelector('.result-head').scrollIntoView({behavior:'smooth',block:'start'})})}
function detail(row,i){$('#detailTitle').textContent=title(row,i);const f=flatten(row);$('#detailBody').innerHTML=`<dl>${Object.entries(f).filter(([,v])=>v!==null&&v!==''&&v!==undefined).map(([k,v])=>`<div class="field"><dt>${esc(k)}</dt><dd>${/^https?:\/\//.test(String(v))?`<a href="${esc(v)}" target="_blank" rel="noopener">${esc(v)}</a>`:esc(v)}</dd></div>`).join('')}</dl>`;$('#detailDialog').showModal()}
async function loadJson(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${url}: HTTP ${r.status}`);return r.json()}
async function boot(){let source='upstream';let payload;try{payload=await loadJson(API_URL)}catch(upstreamError){console.warn('Upstream API unavailable, using local snapshot',upstreamError);source='snapshot';try{payload=await loadJson(LOCAL_URL)}catch(localError){$('#recordCount').textContent='โหลดข้อมูลไม่สำเร็จ';$('#sourceBadge').textContent='API และ snapshot ใช้งานไม่ได้';$('#status').innerHTML=`ไม่สามารถโหลดข้อมูลได้ทั้งจาก API ต้นทางและ snapshot สำรอง<br><small>${esc(localError.message)}</small>`;console.error(localError);return}}
state.rows=rowsFrom(payload);if(!state.rows.length){$('#recordCount').textContent='ไม่พบข้อมูล';$('#status').textContent='โหลดข้อมูลสำเร็จแต่ไม่พบ records ใน response';return}state.filtered=[...state.rows];$('#recordCount').textContent=`ข้อมูล ${state.rows.length.toLocaleString('th-TH')} รายการ`;$('#sourceBadge').textContent=source==='upstream'?'กำลังใช้ข้อมูลสดจาก API ต้นทาง':'API ต้นทางไม่พร้อม — กำลังใช้ snapshot สำรอง';options('#province','province');options('#district','district');options('#agency','agency');render()}
let timer;$('#q').addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(apply,120)});['#province','#district','#agency'].forEach(id=>$(id).addEventListener('change',apply));$('#pageSize').onchange=e=>{state.size=+e.target.value;state.page=1;render()};$('#reset').onclick=()=>{$('#q').value='';['#province','#district','#agency'].forEach(x=>$(x).value='');apply()};$('#clearSearch').onclick=()=>{$('#q').value='';apply();$('#q').focus()};$('#closeDialog').onclick=()=>$('#detailDialog').close();$('#detailDialog').addEventListener('click',e=>{if(e.target===$('#detailDialog'))$('#detailDialog').close()});boot();