const $=s=>document.querySelector(s);
const API='https://260816-karemairodnare.vercel.app/api/v1/records.json',LOCAL='api/v1/records.json';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function rowsFrom(x){if(Array.isArray(x))return x;if(x&&typeof x==='object'){for(const k of ['records','data','items','results'])if(Array.isArray(x[k]))return x[k];for(const v of Object.values(x))if(Array.isArray(v)&&v.length&&typeof v[0]==='object')return v}return[]}
function text(v){return v==null?'':String(v).trim()}function name(r){return text(r.name||r.full_name||r.person_name||r.title||r.id)}function id(r,i){return text(r.id||r.maskedId||i)}
function param(k){return new URLSearchParams(location.search).get(k)||''}function href(next){const p=new URLSearchParams();for(const k of ['province','district','agency']){const v=next[k]??param(k);if(v)p.set(k,v)}return `browse.html?${p}`}
async function load(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error(r.status);return r.json()}
function group(rows,key){const m=new Map();for(const r of rows){const v=text(r[key]);if(v)m.set(v,(m.get(v)||0)+1)}return [...m].sort((a,b)=>a[0].localeCompare(b[0],'th'))}
function crumbs(p,d,a){let h='<a href="browse.html">ทุกจังหวัด</a>';if(p)h+=`<span>›</span><a href="${href({province:p,district:'',agency:''})}">${esc(p)}</a>`;if(d)h+=`<span>›</span><a href="${href({province:p,district:d,agency:''})}">${esc(d)}</a>`;if(a)h+=`<span>›</span><span>${esc(a)}</span>`;$('#breadcrumbs').innerHTML=h}
function cards(items,kind,p,d){$('#browseGrid').innerHTML=items.map(([v,n])=>{const next=kind==='province'?{province:v,district:'',agency:''}:kind==='district'?{province:p,district:v,agency:''}:{province:p,district:d,agency:v};return `<a class="browse-card" data-name="${esc(v.toLocaleLowerCase('th'))}" href="${href(next)}"><strong>${esc(v)}</strong><span>${n.toLocaleString('th-TH')} รายการ</span><b>ดูต่อ →</b></a>`}).join('');$('#recordList').innerHTML='';$('#browseStatus').style.display=items.length?'none':'block'}
function records(rows){$('#browseGrid').innerHTML='';$('#recordList').innerHTML=rows.sort((a,b)=>name(a).localeCompare(name(b),'th')).map((r,i)=>`<a class="record record-link" data-name="${esc(name(r).toLocaleLowerCase('th'))}" href="record.html?id=${encodeURIComponent(id(r,i))}"><div class="record-top"><h3>${esc(name(r))}</h3><span class="num">${esc(text(r.maskedId))}</span></div><div class="summary"><span>จังหวัด: ${esc(text(r.province))}</span><span>อำเภอ: ${esc(text(r.district))}</span><span>หน่วยงาน: ${esc(text(r.agency))}</span></div></a>`).join('');$('#browseStatus').style.display=rows.length?'none':'block'}
async function boot(){let payload,source='ข้อมูลสดจาก API ต้นทาง';try{payload=await load(API)}catch(e){source='snapshot สำรอง';payload=await load(LOCAL)}let rows=rowsFrom(payload),p=param('province'),d=param('district'),a=param('agency');$('#recordCount').textContent=`ข้อมูล ${rows.length.toLocaleString('th-TH')} รายการ`;$('#sourceBadge').textContent=source;crumbs(p,d,a);if(!p){$('#browseTitle').textContent='เรียกดูตามจังหวัด';$('#browseSubtitle').textContent='เลือกจังหวัดเพื่อดูอำเภอ หน่วยงาน และรายการ';cards(group(rows,'province'),'province')}else{rows=rows.filter(r=>text(r.province)===p);if(!d){$('#browseTitle').textContent=p;$('#browseSubtitle').textContent='เลือกอำเภอเพื่อดูหน่วยงาน';cards(group(rows,'district'),'district',p)}else{rows=rows.filter(r=>text(r.district)===d);if(!a){$('#browseTitle').textContent=`${d} • ${p}`;$('#browseSubtitle').textContent='เลือกหน่วยงานเพื่อดูรายการ';cards(group(rows,'agency'),'agency',p,d)}else{rows=rows.filter(r=>text(r.agency)===a);$('#browseTitle').textContent=a;$('#browseSubtitle').textContent=`${d} • ${p} • ${rows.length.toLocaleString('th-TH')} รายการ`;records(rows)}}}$('#browseSearch').oninput=e=>{const q=e.target.value.trim().toLocaleLowerCase('th');document.querySelectorAll('[data-name]').forEach(x=>x.hidden=!!q&&!x.dataset.name.includes(q))}}
boot().catch(e=>{$('#browseStatus').textContent='ไม่สามารถโหลดข้อมูลได้';console.error(e)});